/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  images: { unoptimized: true },
  env: {
    NEXT_PUBLIC_SITE_NAME: process.env.NEXT_PUBLIC_SITE_NAME || 'OMNIUTIL INFRASTRUCTURE',
    NEXT_PUBLIC_SITE_VARIANT: process.env.NEXT_PUBLIC_SITE_VARIANT || 'v9.0-SOUVERAIN',
    NEXT_PUBLIC_BASE_API: process.env.NEXT_PUBLIC_BASE_API || '/api',
    NEXT_PUBLIC_UTIL_PRICE: process.env.NEXT_PUBLIC_UTIL_PRICE || '3.65',
    NEXT_PUBLIC_UTIL_PRICE_ANCHOR: process.env.NEXT_PUBLIC_UTIL_PRICE_ANCHOR || '3650.96',
    NEXT_PUBLIC_CONTRACT_BSC: process.env.NEXT_PUBLIC_CONTRACT_BSC || process.env.CONTRACT_BSC || '0xC8A3EA13b51C5e0a8e5c979d6A0b4BDa6bb1e76B',
    NEXT_PUBLIC_OWNER_WALLET: process.env.NEXT_PUBLIC_OWNER_WALLET || process.env.OWNER_WALLET || '0x40BB46B9D10Dd121e7D2150EC3784782ae648090',
    NEXT_PUBLIC_DEPLOYMENT_BRANCH: process.env.NEXT_PUBLIC_DEPLOYMENT_BRANCH || 'v0/johny-1992',
    NEXT_PUBLIC_FEDERATED_SOURCE: process.env.NEXT_PUBLIC_FEDERATED_SOURCE || 'omniutil-web'
  }
}
module.exports = nextConfig
